name: integrador
description: "A new Flutter project."

# Esta línea evita que el paquete se publique accidentalmente en pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define el número de versión y build de tu aplicación.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencias necesarias para tu proyecto.
dependencies:
  flutter:
    sdk: flutter
  qr: ^2.0.1
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  twilio_flutter: ^0.0.9
  shared_preferences: ^2.2.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+3
  image: ^3.2.0
  mobile_scanner: ^3.5.5
  path_provider: ^2.0.9
  local_auth: ^2.1.8
  url_launcher: ^6.1.5
  fl_chart: ^0.30.0
  geolocator: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^3.0.1

# Sección específica para Flutter packages.
flutter:
  uses-material-design: true

  # Agregar assets al proyecto.
  assets:
    - assets/prediccion_ventas_diarias.json
    - assets/Logo.png
    - assets/LogoUp.png
    - assets/Paulo.jpg
    - assets/Wos.jpg
    - assets/QR.png
    - assets/Duki.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/QR.png"
